const mongoose = require("mongoose");

const MONGODB_URI = "mongodb+srv://tollroster_db_user:I18ubBVvF9pvmVAd@tollrosters.33qlsbs.mongodb.net/?retryWrites=true&w=majority&appName=TollRosters";

const employeeSchema = new mongoose.Schema({
  Employee: String,
  Status: String,
  WorkingSite: String,
  Type: String,
  Department: String,
  Supervisor: String,
  Monday: String,
  Tuesday: String,
  Wednesday: String,
  Thursday: String,
  Friday: String,
  Competencies: [String]
});

const Employee = mongoose.model("Employee", employeeSchema);

const employeeData = [
  {
    "_id": "68af96d8b79de946f0fba989",
    "Employee": "Liam A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Jane Smith",
    "Monday": "10.00 am - 6.00 pm",
    "Tuesday": "10.00 am - 6.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Shipping", "Receiving"]
  },
  {
    "_id": "68af96d8b79de946f0fba98a",
    "Employee": "Emma A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Inbound",
    "Supervisor": "Susan Clark",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Stock Auditing", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba98b",
    "Employee": "Noah A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Susan Clark",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "9.00 am - 5.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Receiving", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba98c",
    "Employee": "Olivia A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Receiving", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba98d",
    "Employee": "Ava A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse A",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Packing", "Inventory Management"]
  },
  {
    "_id": "68af96d8b79de946f0fba98e",
    "Employee": "William A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Labeling", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba98f",
    "Employee": "Sophia A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Inventory Management", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba990",
    "Employee": "James A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Receiving", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba991",
    "Employee": "Isabella A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Casual",
    "Department": "Inbound",
    "Supervisor": "Mark Lee",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Inventory Management", "Labeling"]
  },
  {
    "_id": "68af96d8b79de946f0fba992",
    "Employee": "Benjamin A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Casual",
    "Department": "Inbound",
    "Supervisor": "Susan Clark",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "9.00 am - 5.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Labeling", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba993",
    "Employee": "Mason A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "9.00 am - 5.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Stock Auditing", "Receiving"]
  },
  {
    "_id": "68af96d8b79de946f0fba994",
    "Employee": "Mia A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Inventory Management", "Labeling"]
  },
  {
    "_id": "68af96d8b79de946f0fba995",
    "Employee": "Ethan A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Jane Smith",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Shipping", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba996",
    "Employee": "Charlotte A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Shipping", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba997",
    "Employee": "Logan A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Permanent",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Forklift Operation", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba998",
    "Employee": "Amelia A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "10.00 am - 6.00 pm",
    "Tuesday": "10.00 am - 6.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Stock Auditing", "Labeling"]
  },
  {
    "_id": "68af96d8b79de946f0fba999",
    "Employee": "Lucas A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Inventory Management", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba99a",
    "Employee": "Harper A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse A",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Jane Smith",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Inventory Management", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba99b",
    "Employee": "Elijah A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Forklift Operation", "Labeling"]
  },
  {
    "_id": "68af96d8b79de946f0fba99c",
    "Employee": "Evelyn A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Jane Smith",
    "Monday": "10.00 am - 6.00 pm",
    "Tuesday": "10.00 am - 6.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Receiving", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba99d",
    "Employee": "Liam A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse A",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Susan Clark",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Receiving", "Packing"]
  },
  {
    "_id": "68af96d8b79de946f0fba99e",
    "Employee": "Emma A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Forklift Operation", "Packing"]
  },
  {
    "_id": "68af96d8b79de946f0fba99f",
    "Employee": "Noah A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "9.00 am - 5.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Packing", "Inventory Management"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a0",
    "Employee": "Olivia A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Susan Clark",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Packing", "Receiving"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a1",
    "Employee": "Ava A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Inventory Management", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a2",
    "Employee": "William A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Receiving", "Packing"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a3",
    "Employee": "Sophia A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Stock Auditing", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a4",
    "Employee": "James A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Susan Clark",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Forklift Operation", "Inventory Management"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a5",
    "Employee": "Isabella A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "7.00 am - 3.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Inventory Management", "Packing"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a6",
    "Employee": "Benjamin A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Jane Smith",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Packing", "Receiving"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a7",
    "Employee": "Mason A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Jane Smith",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "6.00 am - 2.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "8.00 am - 4.00 pm",
    "Friday": "6.00 am - 2.00 pm",
    "Competencies": ["Stock Auditing", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a8",
    "Employee": "Mia A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse C",
    "Type": "Casual",
    "Department": "Outbound",
    "Supervisor": "Jane Smith",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Labeling", "Receiving"]
  },
  {
    "_id": "68af96d8b79de946f0fba9a9",
    "Employee": "Ethan A",
    "Status": "Active",
    "WorkingSite": "Warehouse C",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Susan Clark",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Inventory Management", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba9aa",
    "Employee": "Charlotte A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Inbound",
    "Supervisor": "Susan Clark",
    "Monday": "9.00 am - 5.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Forklift Operation", "Stock Auditing"]
  },
  {
    "_id": "68af96d8b79de946f0fba9ab",
    "Employee": "Logan A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Susan Clark",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "9.00 am - 5.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "9.00 am - 5.00 pm",
    "Competencies": ["Stock Auditing", "Labeling"]
  },
  {
    "_id": "68af96d8b79de946f0fba9ac",
    "Employee": "Amelia A",
    "Status": "Active",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Outbound",
    "Supervisor": "Mark Lee",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "7.00 am - 3.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Inventory Management", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba9ad",
    "Employee": "Lucas A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Susan Clark",
    "Monday": "6.00 am - 2.00 pm",
    "Tuesday": "7.00 am - 3.00 pm",
    "Wednesday": "6.00 am - 2.00 pm",
    "Thursday": "10.00 am - 6.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Receiving", "Packing"]
  },
  {
    "_id": "68af96d8b79de946f0fba9ae",
    "Employee": "Harper A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Permanent",
    "Department": "Inbound",
    "Supervisor": "Jane Smith",
    "Monday": "7.00 am - 3.00 pm",
    "Tuesday": "10.00 am - 6.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "10.00 am - 6.00 pm",
    "Competencies": ["Packing", "Shipping"]
  },
  {
    "_id": "68af96d8b79de946f0fba9af",
    "Employee": "Elijah A",
    "Status": "Deactive",
    "WorkingSite": "Warehouse B",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Susan Clark",
    "Monday": "10.00 am - 6.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "10.00 am - 6.00 pm",
    "Thursday": "6.00 am - 2.00 pm",
    "Friday": "8.00 am - 4.00 pm",
    "Competencies": ["Stock Auditing", "Forklift Operation"]
  },
  {
    "_id": "68af96d8b79de946f0fba9b0",
    "Employee": "Evelyn A",
    "Status": "Active",
    "WorkingSite": "Warehouse A",
    "Type": "Casual",
    "Department": "Inventory",
    "Supervisor": "Mark Lee",
    "Monday": "8.00 am - 4.00 pm",
    "Tuesday": "8.00 am - 4.00 pm",
    "Wednesday": "8.00 am - 4.00 pm",
    "Thursday": "9.00 am - 5.00 pm",
    "Friday": "7.00 am - 3.00 pm",
    "Competencies": ["Forklift Operation", "Labeling"]
  }
];

async function seedDatabase() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");
    
    await Employee.deleteMany({});
    console.log("Cleared existing employees");
    
    await Employee.insertMany(employeeData);
    console.log(`Inserted ${employeeData.length} employees`);
    
    await mongoose.disconnect();
    console.log("Database seeded successfully");
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
}

seedDatabase();
